// Code generated by Icestudio 0.3.1
// Sun, 04 Feb 2018 18:48:42 GMT

`default_nettype none

module main #(
 parameter vaaa059 = 8'd126,
 parameter v18b105 = 8'b0001000
) (
 output [7:0] vba1ff6
);
 localparam p0 = v18b105;
 localparam p1 = vaaa059;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 assign vba1ff6 = w4;
 v36d45a #(
  .vc5c8ea(p0)
 ) vae27d1 (
  .v7d356d(w3)
 );
 v36d45a #(
  .vc5c8ea(p1)
 ) v18a321 (
  .v7d356d(w2)
 );
 v819788 v5304aa (
  .v159209(w2),
  .v6c4e35(w3),
  .v59912a(w4)
 );
endmodule

module v36d45a #(
 parameter vc5c8ea = 8'h00
) (
 output [7:0] v7d356d
);
 localparam p1 = vc5c8ea;
 wire [0:7] w0;
 assign v7d356d = w0;
 v36d45a_v465065 #(
  .V(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

module v36d45a_v465065 #(
 parameter V = 0
) (
 output [7:0] k
);
 assign k = V;
endmodule

module v819788 (
 input [7:0] v6c4e35,
 input [7:0] v159209,
 output [7:0] v59912a
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:7] w10;
 wire [0:7] w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:7] w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire [0:7] w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire [0:7] w25;
 wire w26;
 wire [0:7] w27;
 wire [0:7] w28;
 wire [0:7] w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 assign w0 = v6c4e35;
 assign v59912a = w1;
 assign w10 = v159209;
 assign w11 = v159209;
 assign w15 = v159209;
 assign w20 = v159209;
 assign w25 = v159209;
 assign w27 = v159209;
 assign w28 = v159209;
 assign w29 = v159209;
 assign w7 = w5;
 assign w8 = w6;
 assign w11 = w10;
 assign w12 = w6;
 assign w12 = w8;
 assign w13 = w9;
 assign w15 = w10;
 assign w15 = w11;
 assign w17 = w9;
 assign w17 = w13;
 assign w18 = w14;
 assign w20 = w10;
 assign w20 = w11;
 assign w20 = w15;
 assign w22 = w14;
 assign w22 = w18;
 assign w23 = w19;
 assign w25 = w10;
 assign w25 = w11;
 assign w25 = w15;
 assign w25 = w20;
 assign w27 = w10;
 assign w27 = w11;
 assign w27 = w15;
 assign w27 = w20;
 assign w27 = w25;
 assign w28 = w10;
 assign w28 = w11;
 assign w28 = w15;
 assign w28 = w20;
 assign w28 = w25;
 assign w28 = w27;
 assign w29 = w10;
 assign w29 = w11;
 assign w29 = w15;
 assign w29 = w20;
 assign w29 = w25;
 assign w29 = w27;
 assign w29 = w28;
 assign w33 = w19;
 assign w33 = w23;
 assign w34 = w24;
 assign w36 = w24;
 assign w36 = w34;
 assign w37 = w35;
 assign w38 = w4;
 assign w39 = w35;
 assign w39 = w37;
 assign w40 = w4;
 assign w40 = w38;
 assign w41 = w5;
 assign w41 = w7;
 vc98179 vcf97ce (
  .v543360(w2),
  .v92fcd7(w4),
  .v8a69ea(w5),
  .vb0d020(w6),
  .v99a2e5(w10)
 );
 v93b074 vb982da (
  .v33b98d(w0),
  .v4d0c0b(w4),
  .v9bf50f(w5),
  .v30621f(w6),
  .vaad98c(w9),
  .v2fd945(w14),
  .vc1cbd5(w19),
  .v660924(w24),
  .v8c2a58(w35)
 );
 vbc2194 v9a59b8 (
  .vd2f4f6(w1),
  .v8fadf3(w2),
  .v431371(w3),
  .v8fe173(w16),
  .v954afa(w21),
  .v2f760e(w26),
  .vb8624e(w30),
  .v9bb63a(w31),
  .v21b35a(w32)
 );
 vc98179 vc1c0dc (
  .v543360(w3),
  .v92fcd7(w7),
  .v8a69ea(w8),
  .vb0d020(w9),
  .v99a2e5(w11)
 );
 vc98179 v5c8168 (
  .v92fcd7(w12),
  .v8a69ea(w13),
  .vb0d020(w14),
  .v99a2e5(w15),
  .v543360(w16)
 );
 vc98179 vbf1b4e (
  .v92fcd7(w17),
  .v8a69ea(w18),
  .vb0d020(w19),
  .v99a2e5(w20),
  .v543360(w21)
 );
 vc98179 v6ab3d7 (
  .v92fcd7(w22),
  .v8a69ea(w23),
  .vb0d020(w24),
  .v99a2e5(w25),
  .v543360(w26)
 );
 vc98179 v342102 (
  .v99a2e5(w27),
  .v543360(w32),
  .v92fcd7(w33),
  .v8a69ea(w34),
  .vb0d020(w35)
 );
 vc98179 v88fc22 (
  .v99a2e5(w28),
  .v543360(w31),
  .v92fcd7(w36),
  .v8a69ea(w37),
  .vb0d020(w38)
 );
 vc98179 v40e1a8 (
  .v99a2e5(w29),
  .v543360(w30),
  .v92fcd7(w39),
  .v8a69ea(w40),
  .vb0d020(w41)
 );
endmodule

module vc98179 (
 input v92fcd7,
 input v8a69ea,
 input vb0d020,
 input [7:0] v99a2e5,
 output v543360
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire w4;
 assign w0 = v92fcd7;
 assign w1 = v8a69ea;
 assign w2 = vb0d020;
 assign w3 = v99a2e5;
 assign v543360 = w4;
 vc98179_v38eb7f v38eb7f (
  .a(w0),
  .b(w1),
  .c(w2),
  .rule(w3),
  .out(w4)
 );
endmodule

module vc98179_v38eb7f (
 input a,
 input b,
 input c,
 input [7:0] rule,
 output out
);
 assign out = rule[{c, b, a}];
endmodule

module v93b074 (
 input [7:0] v33b98d,
 output v9bf50f,
 output vc1cbd5,
 output v660924,
 output v30621f,
 output vaad98c,
 output v8c2a58,
 output v2fd945,
 output v4d0c0b
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire [0:7] w8;
 assign v9bf50f = w0;
 assign v4d0c0b = w1;
 assign v30621f = w2;
 assign vaad98c = w3;
 assign v2fd945 = w4;
 assign v8c2a58 = w5;
 assign v660924 = w6;
 assign vc1cbd5 = w7;
 assign w8 = v33b98d;
 v93b074_v9469a1 v9469a1 (
  .out0(w0),
  .out7(w1),
  .out1(w2),
  .out2(w3),
  .out3(w4),
  .out6(w5),
  .out5(w6),
  .out4(w7),
  .in(w8)
 );
endmodule

module v93b074_v9469a1 (
 input [7:0] in,
 output out0,
 output out1,
 output out2,
 output out3,
 output out4,
 output out5,
 output out6,
 output out7
);
 assign out0 = in[0];
 assign out1 = in[1];
 assign out2 = in[2];
 assign out3 = in[3];
 assign out4 = in[4];
 assign out5 = in[5];
 assign out6 = in[6];
 assign out7 = in[7];
 
endmodule

module vbc2194 (
 input v8fadf3,
 input v431371,
 input v8fe173,
 input v954afa,
 input v2f760e,
 input v21b35a,
 input v9bb63a,
 input vb8624e,
 output [7:0] vd2f4f6
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign vd2f4f6 = w0;
 assign w1 = v8fadf3;
 assign w2 = v431371;
 assign w3 = v8fe173;
 assign w4 = v954afa;
 assign w5 = v2f760e;
 assign w6 = v21b35a;
 assign w7 = v9bb63a;
 assign w8 = vb8624e;
 vbc2194_v5e3d5c v5e3d5c (
  .out(w0),
  .in0(w1),
  .in1(w2),
  .in2(w3),
  .in3(w4),
  .in4(w5),
  .in5(w6),
  .in6(w7),
  .in7(w8)
 );
endmodule

module vbc2194_v5e3d5c (
 input in0,
 input in1,
 input in2,
 input in3,
 input in4,
 input in5,
 input in6,
 input in7,
 output [7:0] out
);
 assign out={
     in7,
     in6,
     in5,
     in4,
     in3,
     in2,
     in1,
     in0
 };
endmodule
